name: ML Model CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m unittest discover tests/
    
    - name: Run model validation
      run: |
        python validation/model_validator.py
    
    - name: Upload trained model
      uses: actions/upload-artifact@v3
      with:
        name: trained-model
        path: model_*.pth
    
    - name: Upload validation results
      uses: actions/upload-artifact@v3
      with:
        name: validation-results
        path: validation_results.json 